### PR TITLE
Update to node v8 since this is the LTS version by october

### PR DESCRIPTION
**Pull request by anehx**

### CODE REVIEW

**Comment by sliverc** [comment]
Seems v8 only starts to be LTS from 2017-10-31 onwards.

https://github.com/nodejs/Release#release-schedule1

**Comment by sliverc** [comment]
On another note docker container needs to be updated as well.

**Comment by sliverc** [comment]
CI still failing... docker build is actually also failing on docker hub https://hub.docker.com/r/adfinissygroup/timed-frontend/builds/butpqcqd9ksovpukgkfcbnm potentially something which this PR fixes...

**Comment by anehx** [comment]
Closing this in favor of #133

**Pull request closed without merging**
