### PR TITLE
Use chrome and firefox headless for testing

### PR DESCRIPTION
**Pull request by anehx**

### CODE REVIEW

**Comment by czosel** [comment]
Nice! Did you configure this by yourself? Looks exactly like what ember 2.15 ships: https://github.com/adfinis-sygroup/adsycc/pull/38/files

**Comment by anehx** [comment]
I configured it myself. It's basically the recommended options from the travis docs..

**Comment by czosel** [comment]
Alright! Is upgrading to ember 2.15 also something you want to do soon?

**Comment by anehx** [comment]
Yeah sure. I just have not yet found the time for it.

**Pull request merged**
